// Auto-generated by Supabase MCP `generate_typescript_types`.
// Regenerate after every schema change. See AGENTS.md §6 "DB schema".

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      categories: {
        Row: {
          color: string;
          created_at: string;
          icon: string;
          id: string;
          kind: string;
          name: string;
          slug: string;
          sort_order: number;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          color: string;
          created_at?: string;
          icon: string;
          id?: string;
          kind?: string;
          name: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          color?: string;
          created_at?: string;
          icon?: string;
          id?: string;
          kind?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      expense_items: {
        Row: {
          created_at: string;
          expense_id: string;
          id: string;
          line_total: number;
          name: string;
          position: number;
          quantity: number;
          unit_price: number | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          expense_id: string;
          id?: string;
          line_total: number;
          name: string;
          position?: number;
          quantity?: number;
          unit_price?: number | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          expense_id?: string;
          id?: string;
          line_total?: number;
          name?: string;
          position?: number;
          quantity?: number;
          unit_price?: number | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_items_expense_id_fkey';
            columns: ['expense_id'];
            isOneToOne: false;
            referencedRelation: 'expenses';
            referencedColumns: ['id'];
          },
        ];
      };
      expense_splits: {
        Row: {
          created_at: string;
          expense_id: string;
          group_id: string;
          id: string;
          member_id: string;
          share_amount: number;
        };
        Insert: {
          created_at?: string;
          expense_id: string;
          group_id: string;
          id?: string;
          member_id: string;
          share_amount: number;
        };
        Update: {
          created_at?: string;
          expense_id?: string;
          group_id?: string;
          id?: string;
          member_id?: string;
          share_amount?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_splits_expense_id_fkey';
            columns: ['expense_id'];
            isOneToOne: false;
            referencedRelation: 'expenses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expense_splits_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expense_splits_member_id_fkey';
            columns: ['member_id'];
            isOneToOne: false;
            referencedRelation: 'group_members';
            referencedColumns: ['id'];
          },
        ];
      };
      expenses: {
        Row: {
          amount: number;
          category_id: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          group_id: string | null;
          id: string;
          occurred_at: string;
          paid_by_member_id: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          amount: number;
          category_id?: string | null;
          created_at?: string;
          currency: string;
          description?: string | null;
          group_id?: string | null;
          id?: string;
          occurred_at?: string;
          paid_by_member_id?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          amount?: number;
          category_id?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          group_id?: string | null;
          id?: string;
          occurred_at?: string;
          paid_by_member_id?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expenses_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_paid_by_member_id_fkey';
            columns: ['paid_by_member_id'];
            isOneToOne: false;
            referencedRelation: 'group_members';
            referencedColumns: ['id'];
          },
        ];
      };
      group_members: {
        Row: {
          created_at: string;
          display_name: string | null;
          group_id: string;
          id: string;
          invited_by: string | null;
          joined_at: string | null;
          role: string;
          status: string;
          user_id: string | null;
        };
        Insert: {
          created_at?: string;
          display_name?: string | null;
          group_id: string;
          id?: string;
          invited_by?: string | null;
          joined_at?: string | null;
          role?: string;
          status?: string;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          display_name?: string | null;
          group_id?: string;
          id?: string;
          invited_by?: string | null;
          joined_at?: string | null;
          role?: string;
          status?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
        ];
      };
      group_settlements: {
        Row: {
          amount: number;
          created_by: string;
          currency: string;
          from_member_id: string;
          group_id: string;
          id: string;
          settled_at: string;
          to_member_id: string;
        };
        Insert: {
          amount: number;
          created_by: string;
          currency: string;
          from_member_id: string;
          group_id: string;
          id?: string;
          settled_at?: string;
          to_member_id: string;
        };
        Update: {
          amount?: number;
          created_by?: string;
          currency?: string;
          from_member_id?: string;
          group_id?: string;
          id?: string;
          settled_at?: string;
          to_member_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'group_settlements_from_member_id_fkey';
            columns: ['from_member_id'];
            isOneToOne: false;
            referencedRelation: 'group_members';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_settlements_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_settlements_to_member_id_fkey';
            columns: ['to_member_id'];
            isOneToOne: false;
            referencedRelation: 'group_members';
            referencedColumns: ['id'];
          },
        ];
      };
      groups: {
        Row: {
          color: string;
          created_at: string;
          created_by: string;
          icon: string;
          id: string;
          name: string;
          updated_at: string;
        };
        Insert: {
          color?: string;
          created_at?: string;
          created_by: string;
          icon?: string;
          id?: string;
          name: string;
          updated_at?: string;
        };
        Update: {
          color?: string;
          created_at?: string;
          created_by?: string;
          icon?: string;
          id?: string;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          display_name: string | null;
          first_name: string;
          id: string;
          last_name: string;
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          first_name?: string;
          id: string;
          last_name?: string;
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          first_name?: string;
          id?: string;
          last_name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      add_group_member: {
        Args: { p_display_name: string; p_group_id: string };
        Returns: {
          created_at: string;
          display_name: string | null;
          group_id: string;
          id: string;
          invited_by: string | null;
          joined_at: string | null;
          role: string;
          status: string;
          user_id: string | null;
        };
        SetofOptions: {
          from: '*';
          to: 'group_members';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_expense_with_items: {
        Args: {
          p_amount: number;
          p_category_id: string;
          p_currency: string;
          p_description: string;
          p_items?: Json;
          p_occurred_at: string;
        };
        Returns: {
          amount: number;
          category_id: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          group_id: string | null;
          id: string;
          occurred_at: string;
          paid_by_member_id: string | null;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'expenses';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_group: {
        Args: {
          p_color?: string;
          p_icon?: string;
          p_name: string;
          p_placeholders?: Json;
        };
        Returns: {
          color: string;
          created_at: string;
          created_by: string;
          icon: string;
          id: string;
          name: string;
          updated_at: string;
        };
        SetofOptions: {
          from: '*';
          to: 'groups';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_settlement: {
        Args: {
          p_amount: number;
          p_currency: string;
          p_from_member_id: string;
          p_group_id: string;
          p_to_member_id: string;
        };
        Returns: {
          amount: number;
          created_by: string;
          currency: string;
          from_member_id: string;
          group_id: string;
          id: string;
          settled_at: string;
          to_member_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'group_settlements';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_shared_expense: {
        Args: {
          p_amount: number;
          p_category_id: string;
          p_currency: string;
          p_description: string;
          p_group_id: string;
          p_items: Json;
          p_occurred_at: string;
          p_paid_by_member_id: string;
          p_splits: Json;
        };
        Returns: {
          amount: number;
          category_id: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          group_id: string | null;
          id: string;
          occurred_at: string;
          paid_by_member_id: string | null;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'expenses';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      get_group_balances: {
        Args: { p_group_id: string };
        Returns: {
          currency: string;
          member_id: string;
          net: number;
        }[];
      };
      get_personal_totals: {
        Args: { p_from?: string; p_to?: string };
        Returns: {
          count: number;
          currency: string;
          total: number;
        }[];
      };
      invite_group_member: {
        Args: { p_email: string; p_group_id: string };
        Returns: Json;
      };
      is_group_member: {
        Args: { p_group_id: string; p_user_id: string };
        Returns: boolean;
      };
      respond_group_invite: {
        Args: { p_accept: boolean; p_member_id: string };
        Returns: {
          created_at: string;
          display_name: string | null;
          group_id: string;
          id: string;
          invited_by: string | null;
          joined_at: string | null;
          role: string;
          status: string;
          user_id: string | null;
        };
        SetofOptions: {
          from: '*';
          to: 'group_members';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      seed_default_categories: {
        Args: { p_user_id: string };
        Returns: undefined;
      };
      update_expense_with_items: {
        Args: { p_id: string; p_items?: Json; p_patch?: Json };
        Returns: {
          amount: number;
          category_id: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          group_id: string | null;
          id: string;
          occurred_at: string;
          paid_by_member_id: string | null;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'expenses';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      update_shared_expense: {
        Args: {
          p_id: string;
          p_items?: Json;
          p_paid_by_member_id?: string;
          p_patch?: Json;
          p_splits?: Json;
        };
        Returns: {
          amount: number;
          category_id: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          group_id: string | null;
          id: string;
          occurred_at: string;
          paid_by_member_id: string | null;
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'expenses';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      user_exists_by_email: { Args: { p_email: string }; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
